### ISSUE TITLE
Add rule-of-third lines while cropping

### ISSUE THREAD

**Issue by toddmyphoto** [DominicTobias/react-image-crop#187]
A few other cropping libraries allow you to hide and show rule-of-third lines while cropping (dragging the crop area, drawing a new one, or dragging a handle). Would love to see that feature in this library.

**Comment by elektronaut** [comment]
Having built in support for this would be great, but it's also doable with CSS. Here's an example in SCSS:

```scss
.ReactCrop__crop-selection {
  &:before, &:after {
    content: "";
    position: absolute;
    border-color: rgba(200, 200, 200, 0.75);
    border-style: solid;
  }
  &:before {
    border-left-width: 1px;
    border-right-width: 1px;
    width: 33.33%;
    height: 100%;
    left: 33.33%;
  }
  &:after {
    border-top-width: 1px;
    border-bottom-width: 1px;
    width: 100%;
    height: 33.33%;
    top: 33.33%;
  }
}
```

If you want it just while manipulating the selection, change the rule to: 
```scss
.ReactCrop--active .ReactCrop__crop-selection {
  ...
}
```
