### ISSUE TITLE
Feature Request: Crop 2 images(background-image and image) into a single output image.

### ISSUE THREAD

**Issue by svenkatesh-nyros** [DominicTobias/react-image-crop#237]
Is it possible to provide the source image in a existing background image to crop them into single image using this package.
following is the example working urls for making this feature.

http://subinsb.com/create-profile-picture-framer-web-app/

Git url: https://github.com/subins2000/profile-picture-framer

can this feature implemented in your package ?

**Comment by DominicTobias** [comment]
Hi,

This component crops an image, what you do before or after that is up to you. I have no intention of implementing something so specific in the library as there is no reason to put it in here. I didn't understand how you aim to achieve this technically: as two images which are always separate (one on top of the other), or as a single image where one is programatically merged with the other.

If it's the first one then it shouldn't be hard to do in pure css - e.g.

```css
.ReactCrop__image {
  position: relative;
}
.ReactCrop__image::after {
  display: block;
  content: '';
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  background-image: url(x);
}
```

Just untested pseudo code but you get the idea! I would style based on a custom class passed into the component too.
