### ISSUE TITLE
Target classNames with css modules

### ISSUE THREAD

**Issue by hannanel100** [DominicTobias/react-image-crop#480]
Using css modules i wasn't able to add a class and change the styles using the method showed in the documentation.

Am i doing something wrong? Is this not supported?

**Comment by DominicTobias** [comment]
Both the `className` and `style` prop are passed to the root component so you should be able to. How did you try?

**Comment by hannanel100** [comment]
I created a sandbox: https://codesandbox.io/s/nifty-glade-1jzo0v?file=/src/App.css when using normal css, i am able to target the border and box-shadow and change them, but when using css modules it doesn't work.

**Comment by DominicTobias** [comment]
You can target the outer element:

```css
.crop {
  border: 5px solid red;
}
```

if you want to target a class on an inner element you have to specify that CSS modules shouldn't hash it:

```css
.crop :global(.ReactCrop__crop-selection) {
  border: 5px solid red;
}
```
