### ISSUE TITLE
Crop handles are not overflowing

### ISSUE THREAD

**Issue by hugomallet** [DominicTobias/react-image-crop#495]
Hi,

the crop handles are not entirely visible on images edges. And removing the overflow: hidden makes the shadow overflowing.

<img width="218" alt="image" src="https://user-images.githubusercontent.com/1888705/175053778-f106be47-a498-47ac-90ca-8f9551a09507.png">
<img width="404" alt="image" src="https://user-images.githubusercontent.com/1888705/175053884-d77121cc-121b-4a31-aca4-905c646cb0d2.png">

Any idea ?

**Comment by ssadler** [comment]
Try this:

```css
.ReactCrop {                    
  overflow: visible !important
}
```
