### ISSUE TITLE
Overflow conflicting with shadow (overlay)

### ISSUE THREAD

**Issue by RewriteH** [DominicTobias/react-image-crop#530]
I have design-case in which draggable arrows should be visible outside crop container. I set `overflow: initial` but after that shadow (overlay) is going to completely outside crop for a whole window.
I have tried many paths to figure it out, also i checkout react-cropper for see how they implemented this behavior

They just put another image in a crop selection div and recalcing his dimensions. After that they just show dark overlay for a whole crop component.
I know this behavior is needed for 0.01% cases, but if this can me implemented in react-image-crop it will be very good and handy :)

**Comment by DominicTobias** [comment]
Yes I would like to solve this problem, as you said double image can work but was hesitant to load the image twice due to increased resources used especially on mobile. The alternative is to make a shape with a rectangular hole in it (e.g css clip path or an SVG) but again need to check the perf. I’m away without a computer until mid Feb though so can’t do any work on it yet.

**Comment by RewriteH** [comment]
Here's is a workaround for who's faced the same issue

```
export const Crop: FC<CropProps> = ({ className, src, ...props }) => {
  const [crop, setCrop] = useState<PercentCrop | undefined>()

  const { ref, width, height } = useResizeObserver<HTMLDivElement>()

  const cropValue = props.crop ?? crop

  const cropRef = useRef<ReactCrop | null>(null)
  const viewBoxRef = useRef<HTMLImageElement | null>(null)
  const cropImgRef = useRef<HTMLImageElement | null>(null)

  const classNames = cn(styles.crop, className)

  const setViewBox = useCallback(
    (crop: CropValue) => {
      if (!crop || !width || !height) return
      const { current: cropImage } = cropImgRef

      if (!cropImage) return

      const croppedX = width * (crop.x / 100)
      const croppedY = height * (crop.y / 100)

      const translateX = -croppedX
      const translateY = -croppedY

      cropImage.style.transform = `translateX(${translateX}px) translateY(${translateY}px)`
    },
    [props.crop]
  )

  const onChange: ReactCropProps['onChange'] = (pixelCrop, percentCrop) => {
    if (!width || !height) return

    if (!props.crop) {
      setCrop(percentCrop)
      setViewBox(percentCrop)
    }

    props.onChange?.(pixelCrop, percentCrop)
  }

  useLayoutEffect(() => {
    if (!cropValue) return

    setViewBox(cropValue)
  }, [cropValue])

  return (
    <ReactCrop
      ref={cropRef}
      className={classNames}
      crop={props.crop ?? crop}
      onChange={onChange}
      minHeight={50}
      minWidth={50}
      renderSelectionAddon={() => {
        return (
          <img
            style={{ height, width }}
            ref={cropImgRef}
            src={src}
            className={styles.cropImage}
          />
        )
      }}
    >
      <img
        ref={(originalRef) => {
          ref(originalRef)
          viewBoxRef.current = originalRef
        }}
        src={src}
      />
    </ReactCrop>
  )
}
```

**Comment by DominicTobias** [comment]
Sorry forgot to reply: I tried implementing this and it was trickier than I thought. The problems are:
- Circular crop
- Browser support for CSS shapes

Here's a solution for now using CSS `clip-path` which is probably the way I'll implemented it. I just need to consider circular crop and browser support and performance first.

However this solution seems to work in latest Safari, FF, and Chrome:

First override some CSS:

```css
.ReactCrop {
  overflow: initial;
}

.ReactCrop__crop-selection {
  box-shadow: none;
}

.ReactCrop__crop-mask {
  position: absolute;
  inset: 0;
  background: red;
  clip-path: polygon(
    0% 0%,
    0% 100%,
    var(--pos-x) 100%,
    var(--pos-x) var(--pos-y),
    calc(var(--pos-x) + var(--pos-width)) var(--pos-y),
    calc(var(--pos-x) + var(--pos-width)) calc(var(--pos-y) + var(--pos-height)),
    var(--pos-x) calc(var(--pos-y) + var(--pos-height)),
    var(--pos-x) 100%,
    100% 100%,
    100% 0%
  );
}
```

Finally render the crop-mask and set the crop CSS variables:

```jsx
<ReactCrop
  ...otherProps...
  style={{
    '--pos-x': `${crop?.x}%`,
    '--pos-y': `${crop?.y}%`,
    '--pos-width': `${crop?.width}%`,
    '--pos-height': `${crop?.height}%`,
  }}
>
  <img ...otherProps... />
  <div className="ReactCrop__crop-mask" />
</ReactCrop>
```

If you're using pixel crops don't forget to change `%` to `px` in the CSS variables above.

Demo: https://codesandbox.io/s/react-image-crop-demo-with-overflow-allowed-8sd6k6?file=/src/App.tsx:4097-4762

**Comment by DominicTobias** [comment]
Ignore my previous post I realized I was being daft. I published a change which removes `overflow:hidden` in v `10.0.10`

**Comment by DominicTobias** [comment]
Nevermind my fix had a major problem 🤦‍♂️. So the solution I posted before still applies:

```css
.ReactCrop {
  overflow: initial;
}

.ReactCrop__crop-selection {
  box-shadow: none;
}

.ReactCrop__crop-mask {
  position: absolute;
  inset: 0;
  background: rgba(0, 0, 0, 0.5);
  clip-path: polygon(
    0% 0%,
    0% 100%,
    var(--pos-x) 100%,
    var(--pos-x) var(--pos-y),
    calc(var(--pos-x) + var(--pos-width)) var(--pos-y),
    calc(var(--pos-x) + var(--pos-width)) calc(var(--pos-y) + var(--pos-height)),
    var(--pos-x) calc(var(--pos-y) + var(--pos-height)),
    var(--pos-x) 100%,
    100% 100%,
    100% 0%
  );
}
```

```jsx
<ReactCrop
  ...otherProps...
  style={
    crop
      ? {
          '--pos-x': `${crop.x}%`,
          '--pos-y': `${crop.y}%`,
          '--pos-width': `${crop.width}%`,
          '--pos-height': `${crop.height}%`,
        }
      : undefined
  }
>
  <img ...otherProps.../>
  {crop && <div className="ReactCrop__crop-mask" />}
</ReactCrop>
```

https://codesandbox.io/s/react-image-crop-demo-with-overflow-allowed-8sd6k6
