### ISSUE TITLE
Crop doesn't hide even if keepSelection set to false

### ISSUE THREAD

**Issue by DvirH** [DominicTobias/react-image-crop#58]
I tried to create a toggle button of crop mode.
When I select an area and click outside on the toggle button I disable the crop, but the selection is still active. Is there anyway to workaround this?

**Comment by DominicTobias** [comment]
I think you are confused about the behaviour of these two options:

keepSelection - this stops the crop from disappearing if the user clicks outside the crop (somewhere on the image)

disabled - this stops the user from being able to modify the crop, but it doesn't hide or destroy the crop

If you want to temporarily hide it then I recommend using css, try this:

```css
.ReactCrop--crop-selection {
   display: none;
}
.ReactCrop--image-copy {
    -webkit-clip-path: none;
    clip-path: none;
}
```
