### ISSUE TITLE
Mask overlay leaves a 1px-high area over the image

### ISSUE THREAD

**Issue by tmarcinkowski-logitech** [dominictobias/react-image-crop#611]
Hi
I have a customized instance of the cropper, and changing the overlay color to white revealed an issue where the image doesn't cover the whole image, despite having 100% height, leaving a 1px-high line. The video at the bottom shows the issue.

For me, the hacky workaround was to expand it slightly, but you might want to investigate it properly.

```css
  & .ReactCrop__crop-mask,
  & .ReactCrop__crop-mask mask > rect:first-child {
    height: 100.1%;
  }
```

https://github.com/user-attachments/assets/7283c54a-e02b-4381-9f8a-649707c47902
